import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CopyPlus, Download, FileText, Printer, Save } from "lucide-react";
import { toPng } from "html-to-image";
import { jsPDF } from "jspdf";
import { toast } from "sonner";
import { DocumentPaper } from "@/components/document-paper";
import { SavedDocumentsSidebar } from "@/components/saved-documents-sidebar";
import { StartupExperience } from "@/components/startup-experience";
import { Button } from "@/components/ui/button";
import { useHistoryState } from "@/hooks/use-history-state";
import { useSavedDocuments } from "@/hooks/use-saved-documents";
import { CURRENCIES, DOC_LABELS, PAPER_SIZES, createBlankDocumentState, safeFileName, uid, type DocType, type PaperSizeKey, type SavedDocument } from "@/lib/document";

const DOC_ORDER: DocType[] = ["invoice", "quotation", "dc", "tax"]; const PAPER_ORDER: PaperSizeKey[] = ["A4", "A5", "Letter", "Legal"];
type SavePickerWindow = Window & typeof globalThis & {
  showSaveFilePicker?: (options: { suggestedName: string; types: Array<{ description: string; accept: Record<string, string[]> }> }) => Promise<{
    createWritable: () => Promise<{ write: (blob: Blob) => Promise<void>; close: () => Promise<void> }>;
  }>;
};
async function saveBlob(blob: Blob, name: string, description: string, extension: string) { const picker = (window as SavePickerWindow).showSaveFilePicker; if (picker) { const handle = await picker({ suggestedName: name, types: [{ description, accept: { [blob.type]: [extension] } }] }); const writable = await handle.createWritable(); await writable.write(blob); await writable.close(); return } const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url) }

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "Document Studio | 8 Ways Communications" }, { name: "description", content: "Create and manage print-ready invoices, quotations, delivery challans, and sales tax invoices." }, { property: "og:title", content: "Document Studio | 8 Ways Communications" }, { property: "og:description", content: "Create and manage professional print-ready business documents." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Index });

function Index() {
  const [docType, setDocType] = useState<DocType>("invoice"); const [paperSize, setPaperSize] = useState<PaperSizeKey>("A4"); const { state, setState, reset, undo, redo } = useHistoryState(createBlankDocumentState); const [activeId, setActiveId] = useState<string | null>(null); const [activeFolder, setActiveFolder] = useState("General"); const { documents, setDocuments } = useSavedDocuments();
  const paper = PAPER_SIZES[paperSize]; const paperStyle = useMemo(() => ({ "--paper-width": paper.width, "--paper-height": paper.height, "--paper-scale": paper.scale } as CSSProperties), [paper]);
  const newDocument = useCallback(() => { setActiveId(null); setActiveFolder("General"); setDocType("invoice"); setPaperSize("A4"); reset(createBlankDocumentState()) }, [reset]);
  const openDocument = useCallback((document: SavedDocument) => { setActiveId(document.id); setActiveFolder(document.folder); setDocType(document.docType); setPaperSize(document.paperSize); reset(document.state) }, [reset]);
  const renderPdf = useCallback(async () => { const elements = Array.from(document.querySelectorAll<HTMLElement>("[data-pdf-page]")); if (!elements.length) throw new Error("No document pages"); elements.forEach((element) => element.classList.add("exporting")); try { const [width, height] = paper.pdf; const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: [width, height], compress: true }); let index = 0; for (const element of elements) { const dataUrl = await toPng(element, { pixelRatio: 1.75, cacheBust: false, backgroundColor: "white", skipFonts: true }); if (index > 0) pdf.addPage([width, height], "portrait"); pdf.addImage(dataUrl, "PNG", 0, 0, width, height, undefined, "FAST"); index++ } return pdf.output("blob") } finally { elements.forEach((element) => element.classList.remove("exporting")) } }, [paper.pdf]);
  const persist = useCallback(async (asCopy = false) => { const now = Date.now(); const current = !asCopy ? documents.find((entry) => entry.id === activeId) : undefined; const saved: SavedDocument = { id: current?.id ?? uid(), title: current?.title ?? `${DOC_LABELS[docType]} ${state.meta.number || documents.length + 1}`, docType, paperSize, state, folder: activeFolder, createdAt: current?.createdAt ?? now, updatedAt: now }; let pdfData: string | undefined; if (window.desktop) { const blob = await renderPdf(); pdfData = await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(blob) }); await window.desktop.saveDocument(saved, pdfData) } setDocuments((list) => [saved, ...list.filter((entry) => entry.id !== saved.id)].sort((a, b) => b.updatedAt - a.updatedAt)); setActiveId(saved.id); toast.success(asCopy ? "Copy saved." : "Document saved.") }, [activeFolder, activeId, docType, documents, paperSize, renderPdf, setDocuments, state]);
  const downloadPdf = useCallback(async () => { try { const blob = await renderPdf(); const name = `${safeFileName(docType, state.meta.number)}.pdf`; if (window.desktop) { const reader = new FileReader(); reader.onload = async () => { await window.desktop?.savePdf(name, String(reader.result)); toast.success("PDF saved.") }; reader.readAsDataURL(blob) } else { await saveBlob(blob, name, "PDF document", ".pdf"); toast.success("PDF saved.") } } catch { toast.error("The PDF could not be saved.") } }, [docType, renderPdf, state.meta.number]);
  const printDocument = useCallback(() => window.print(), []);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (!(event.ctrlKey || event.metaKey)) return; const key = event.key.toLowerCase(); if (key === "p") { event.preventDefault(); printDocument() } else if (key === "s") { event.preventDefault(); void persist(event.shiftKey && Boolean(activeId)) } else if (key === "n") { event.preventDefault(); newDocument() } else if (key === "f") { event.preventDefault(); document.getElementById("document-search-input")?.focus() } else if (key === "z") { event.preventDefault(); event.shiftKey ? redo() : undo() } else if (key === "y") { event.preventDefault(); redo() } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler) }, [activeId, newDocument, persist, printDocument, redo, undo]);
  const createFolder = async () => { const name = window.prompt("Folder name"); if (!name?.trim()) return; setActiveFolder(name.trim()); if (window.desktop) await window.desktop.createFolder(docType, name.trim()); toast.success(`Folder “${name.trim()}” selected.`) };
  return <div className="studio-shell"><style>{`@media print { @page { size: ${paper.page} portrait; margin: 0; } }`}</style><StartupExperience/><SavedDocumentsSidebar documents={documents} activeId={activeId} onNew={newDocument} onOpen={openDocument} onRename={(id, title) => setDocuments((list) => list.map((entry) => entry.id === id ? { ...entry, title } : entry))} onDelete={async (entry) => { if (!window.confirm("Delete this saved document?")) return; if (window.desktop) await window.desktop.deleteDocument(entry); setDocuments((list) => list.filter((item) => item.id !== entry.id)); if (activeId === entry.id) newDocument() }} onCreateFolder={() => void createFolder()}/><div className="studio-main"><header className="no-print toolbar"><div className="toolbar-inner"><div className="studio-brand"><FileText size={19}/><span>Document Studio</span></div><div className="toolbar-actions"><label className="select-control"><span>Choose Document</span><select value={docType} onChange={(event) => setDocType(event.target.value as DocType)} aria-label="Choose Document">{DOC_ORDER.map((type) => <option key={type} value={type}>{DOC_LABELS[type]}</option>)}</select></label><label className="select-control"><span>Currency</span><select value={state.currency} onChange={(event) => setState((current) => ({ ...current, currency: event.target.value }))} aria-label="Currency">{CURRENCIES.map((currency) => <option key={currency} value={currency}>{currency.trim()}</option>)}</select></label><label className="select-control"><span>Paper</span><select value={paperSize} onChange={(event) => setPaperSize(event.target.value as PaperSizeKey)} aria-label="Paper size">{PAPER_ORDER.map((size) => <option key={size}>{size}</option>)}</select></label><label className="select-control"><span>Custom Pages</span><input type="number" min={1} max={99} value={state.minimumPages} onChange={(event) => setState((current) => ({ ...current, minimumPages: Math.max(1, event.target.valueAsNumber || 1) }))} aria-label="Minimum custom pages"/></label><Button type="button" variant="secondary" onClick={() => void persist(false)}><Save size={16}/> Save Document</Button>{activeId && <Button type="button" variant="secondary" onClick={() => void persist(true)}><CopyPlus size={16}/> Save As…</Button>}<Button type="button" variant="secondary" onClick={() => void downloadPdf()}><Download size={16}/> Download PDF</Button><Button type="button" onClick={printDocument}><Printer size={16}/> Print</Button></div></div></header><main className="print-area"><DocumentPaper docType={docType} state={state} setState={setState} paperStyle={paperStyle} paperSize={paperSize}/></main></div></div>;
}