import { memo, useMemo, type CSSProperties, type Dispatch, type SetStateAction } from "react";
import { Globe2, Mail, MapPin, Phone, Plus, Trash2 } from "lucide-react";
import logoAsset from "@/assets/company-logo.png.asset.json";
import { DOC_LABELS, PAPER_SIZES, money, uid, type DocState, type DocType, type LineItem, type PaperSizeKey } from "@/lib/document";
import { Button } from "@/components/ui/button";
import { AreaField, NumberField, TextField } from "@/components/field";

interface Props { docType: DocType; state: DocState; setState: Dispatch<SetStateAction<DocState>>; paperStyle: CSSProperties; paperSize: PaperSizeKey }

export function DocumentPaper({ docType, state, setState, paperStyle, paperSize }: Props) {
  const capacity = PAPER_SIZES[paperSize].rows;
  const pages = useMemo(() => {
    const chunks: LineItem[][] = [];
    for (let index = 0; index < state.items.length; index += capacity) chunks.push(state.items.slice(index, index + capacity));
    while (chunks.length < state.minimumPages) chunks.push([]);
    return chunks.length ? chunks : [[]];
  }, [capacity, state.items, state.minimumPages]);
  const updateItem = (id: string, patch: Partial<LineItem>) => setState((current) => ({ ...current, items: current.items.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const removeItem = (id: string) => setState((current) => ({ ...current, items: current.items.length > 1 ? current.items.filter((item) => item.id !== id) : current.items }));
  const addItem = () => setState((current) => ({ ...current, items: [...current.items, { id: uid(), description: "", unit: "pcs", qty: 1, rate: 0 }] }));
  return <div id="document-pages" className="document-pages">
    {pages.map((items, pageIndex) => <DocumentPage key={`${pageIndex}-${items[0]?.id ?? "empty"}`} docType={docType} state={state} setState={setState} items={items} itemOffset={pageIndex * capacity} pageIndex={pageIndex} pageCount={pages.length} paperStyle={paperStyle} paperSize={paperSize} updateItem={updateItem} removeItem={removeItem} addItem={addItem}/>) }
  </div>;
}

interface PageProps extends Props { items: LineItem[]; itemOffset: number; pageIndex: number; pageCount: number; updateItem: (id: string, patch: Partial<LineItem>) => void; removeItem: (id: string) => void; addItem: () => void }
const DocumentPage = memo(function DocumentPage({ docType, state, setState, items, itemOffset, pageIndex, pageCount, paperStyle, paperSize, updateItem, removeItem, addItem }: PageProps) {
  const first = pageIndex === 0; const last = pageIndex === pageCount - 1; const isTax = docType === "tax"; const isChallan = docType === "dc"; const isQuotation = docType === "quotation"; const showAmounts = !isChallan;
  const subtotal = state.items.reduce((sum, item) => sum + (item.qty || 0) * (item.rate || 0), 0); const taxAmount = showAmounts ? subtotal * ((state.taxRate || 0) / 100) : 0; const total = subtotal + taxAmount;
  const set = <K extends keyof DocState>(key: K, value: DocState[K]) => setState((current) => ({ ...current, [key]: value }));
  return <article className={`paper paper-${paperSize.toLowerCase()}`} style={paperStyle} data-pdf-page>
    <div className="top-accent"/><div className="document-content">
      <header className="document-header"><img src={logoAsset.url} alt="8 Ways Communications" className="document-logo"/></header>
      {<><section className="identity-grid"><div className="bill-to"><h2>Bill To</h2><TextField value={state.client.name} onChange={(value) => set("client", { ...state.client, name: value })} placeholder="Client name" ariaLabel="Client name" className="client-name"/><ContactRow icon={Phone}><TextField value={state.client.phone} onChange={(value) => set("client", { ...state.client, phone: value })} placeholder="Phone number" ariaLabel="Client phone"/></ContactRow><ContactRow icon={Mail}><TextField value={state.client.email} onChange={(value) => set("client", { ...state.client, email: value })} placeholder="Email address" ariaLabel="Client email"/></ContactRow><ContactRow icon={MapPin}><AreaField value={state.client.address} onChange={(value) => set("client", { ...state.client, address: value })} placeholder="Client address" ariaLabel="Client address"/></ContactRow><ContactRow icon={Globe2}><TextField value={state.client.website} onChange={(value) => set("client", { ...state.client, website: value })} placeholder="Website" ariaLabel="Client website"/></ContactRow></div>
        <div className="document-meta"><MetaRow label={isTax ? "STI #" : isQuotation ? "Quotation #" : isChallan ? "Challan #" : "Invoice #"}><TextField value={state.meta.number} onChange={(value) => set("meta", { ...state.meta, number: value })} placeholder="#351-34" ariaLabel="Document number" align="right"/></MetaRow><MetaRow label="Document Date"><TextField value={state.meta.date} onChange={(value) => set("meta", { ...state.meta, date: value })} placeholder="DD/MM/YYYY" ariaLabel="Document date" align="right"/></MetaRow>{!isChallan && <MetaRow label={isQuotation ? "Valid Until" : "Due Date"}><TextField value={isQuotation ? state.meta.validUntil : state.meta.dueDate} onChange={(value) => set("meta", { ...state.meta, [isQuotation ? "validUntil" : "dueDate"]: value })} placeholder="DD/MM/YYYY" ariaLabel={isQuotation ? "Valid until" : "Due date"} align="right"/></MetaRow>}<h1 className={`document-title document-title-${docType}`}>{DOC_LABELS[docType]}</h1></div></section>
        {isTax && <section className="detail-strip two-columns"><InlineDetail label="NTN" value={state.meta.ntn} onChange={(value) => set("meta", { ...state.meta, ntn: value })}/><InlineDetail label="STRN" value={state.meta.strn} onChange={(value) => set("meta", { ...state.meta, strn: value })}/></section>}
         {first && isChallan && <section className="detail-strip three-columns"><InlineDetail label="Dispatch Via" value={state.dispatch.method} onChange={(value) => set("dispatch", { ...state.dispatch, method: value })}/><InlineDetail label="Vehicle No." value={state.dispatch.vehicleNo} onChange={(value) => set("dispatch", { ...state.dispatch, vehicleNo: value })}/><InlineDetail label="Gate Pass No." value={state.dispatch.gatePassNo} onChange={(value) => set("dispatch", { ...state.dispatch, gatePassNo: value })}/></section>}</>}
      <section className="items-section"><table><thead><tr><th className="number-col">No</th><th>Description</th><th className="unit-col">Unit</th><th className="qty-col">Qty</th>{showAmounts && <th className="unit-price-col">Unit Price</th>}{showAmounts && <th className="amount-col">Amount</th>}<th className="no-print action-col"/></tr></thead><tbody>{items.map((item, index) => <tr key={item.id}><td className="number-col">{itemOffset + index + 1}</td><td className="description-col"><AreaField value={item.description} onChange={(value) => updateItem(item.id, { description: value })} placeholder="Item or service description" ariaLabel={`Description for row ${itemOffset + index + 1}`}/></td><td className="unit-col"><TextField value={item.unit} onChange={(value) => updateItem(item.id, { unit: value })} placeholder="pcs" ariaLabel="Unit" align="center"/></td><td className="qty-col"><NumberField value={item.qty} onChange={(value) => updateItem(item.id, { qty: value })} ariaLabel="Quantity"/></td>{showAmounts && <td className="unit-price-col unit-price"><NumberField value={item.rate} onChange={(value) => updateItem(item.id, { rate: value })} ariaLabel="Unit price" step={.01}/></td>}{showAmounts && <td className="amount-col line-total">{money((item.qty || 0) * (item.rate || 0), state.currency)}</td>}<td className="no-print action-col"><Button type="button" size="icon" variant="danger" onClick={() => removeItem(item.id)} aria-label="Remove row"><Trash2 size={15}/></Button></td></tr>)}</tbody></table>{last && <Button type="button" variant="ghost" className="no-print add-line" onClick={addItem}><Plus size={15}/> Add line item</Button>}</section>
      {last && <>{showAmounts && <section className="totals"><div className="total-row"><span>Sub Total</span><strong>{money(subtotal, state.currency)}</strong></div><div className="total-row"><span>{isTax ? "Sales Tax" : "Taxes"}<span className="tax-editor"> (<NumberField value={state.taxRate} onChange={(value) => set("taxRate", value)} ariaLabel="Tax rate percent"/>%)</span></span><strong>{money(taxAmount, state.currency)}</strong></div><div className="total-banner"><span>{isQuotation ? "Estimate" : "Total"}</span><strong>{money(total, state.currency)}</strong></div></section>}<section className="closing-content"><div className="terms-block"><h3>Terms &amp; Conditions</h3><AreaField value={state.terms} onChange={(value) => set("terms", value)} placeholder="Payment terms" ariaLabel="Terms and conditions"/></div><div className="payment-info"><div className="payment-details"><strong>Payment Info</strong><AreaField value={state.paymentInfo} onChange={(value) => set("paymentInfo", value)} placeholder="Bank, account, or payment instructions" ariaLabel="Payment information"/></div><div className="signature-block">Authorized Signature</div></div><div className="thank-you"><span>{isChallan ? "Received in Good Order" : "Thanks for your Business!"}</span></div></section></>}
    </div>{last && <footer className="document-footer"><FooterField icon={MapPin}><AreaField value={state.footer.address} onChange={(value) => set("footer", { ...state.footer, address: value })} placeholder="Business address" ariaLabel="Business address"/></FooterField><FooterField icon={Phone}><TextField value={state.footer.phone} onChange={(value) => set("footer", { ...state.footer, phone: value })} placeholder="Phone" ariaLabel="Business phone"/></FooterField><FooterField icon={Mail}><TextField value={state.footer.email} onChange={(value) => set("footer", { ...state.footer, email: value })} placeholder="Email" ariaLabel="Business email"/></FooterField></footer>}<div className="page-number">Page {pageIndex + 1} of {pageCount}</div>
  </article>;
});

function ContactRow({ icon: Icon, children }: { icon: typeof Phone; children: React.ReactNode }) { return <div className="contact-row"><Icon size={14}/>{children}</div> }
function MetaRow({ label, children }: { label: string; children: React.ReactNode }) { return <div className="meta-row"><span>{label}</span><div>{children}</div></div> }
function InlineDetail({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div><strong>{label}</strong><TextField value={value} onChange={onChange} placeholder="—" ariaLabel={label}/></div> }
function FooterField({ icon: Icon, children }: { icon: typeof Phone; children: React.ReactNode }) { return <div className="footer-field"><Icon size={18}/>{children}</div> }