import { useEffect, useState } from "react";
import { ArchiveRestore, FolderOpen, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

export function StartupExperience() {
  const [phase, setPhase] = useState<"splash" | "setup" | "done">("splash");
  const [busy, setBusy] = useState(false);
  useEffect(() => { const timer = window.setTimeout(async () => { if (!window.desktop) return setPhase("done"); const settings = await window.desktop.getSettings(); setPhase(settings.initialized ? "done" : "setup") }, 3000); return () => window.clearTimeout(timer) }, []);
  const fresh = async () => { if (!window.desktop) return setPhase("done"); setBusy(true); const root = await window.desktop.chooseDataRoot(); if (root) { await window.desktop.initialize(root); setPhase("done") } setBusy(false) };
  const restore = async () => { if (!window.desktop) return; setBusy(true); const result = await window.desktop.restore(); if (result) setPhase("done"); setBusy(false) };
  if (phase === "done") return null;
  if (phase === "splash") return <div className="startup-overlay startup-splash" role="status"><div className="splash-mark"><Sparkles size={28}/></div><h1>Document Studio</h1><p>Document Generated by M. Muneeb Ahmed</p></div>;
  return <div className="startup-overlay"><section className="setup-dialog" role="dialog" aria-modal="true" aria-labelledby="setup-title"><span>First launch</span><h1 id="setup-title">Set up your workspace</h1><p>Start with an empty library or restore a previous Document Studio folder.</p><div className="setup-actions"><Button type="button" onClick={fresh} disabled={busy}><FolderOpen size={18}/> Start Fresh Setup</Button><Button type="button" variant="outline" onClick={restore} disabled={busy}><ArchiveRestore size={18}/> Restore Data from Existing Folder</Button></div></section></div>;
}