import { useEffect, useState } from "react";
import { ArchiveRestore, FolderOpen, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

type StartupPhase = "splash" | "setup" | "done";

export function StartupExperience() {
  const [phase, setPhase] = useState<StartupPhase>("splash");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    const active = phase !== "done";
    document.documentElement.classList.toggle("startup-active", active);
    document.body.classList.toggle("startup-active", active);
    return () => {
      document.documentElement.classList.remove("startup-active");
      document.body.classList.remove("startup-active");
    };
  }, [phase]);

  useEffect(() => {
    let mounted = true;
    let timer: number | undefined;

    if (window.desktop) {
      void window.desktop.getSettings()
        .then((settings) => {
          if (mounted) setPhase(settings.initialized ? "done" : "setup");
        })
        .catch((error: unknown) => {
          console.error("Could not read desktop startup settings:", error);
          if (mounted) setPhase("setup");
        });
    } else {
      timer = window.setTimeout(() => {
        if (mounted) setPhase("done");
      }, 3000);
    }

    return () => {
      mounted = false;
      if (timer !== undefined) window.clearTimeout(timer);
    };
  }, []);

  const fresh = async () => {
    if (!window.desktop) {
      setPhase("done");
      return;
    }
    setBusy(true);
    try {
      const root = await window.desktop.chooseDataRoot();
      if (root) {
        await window.desktop.initialize(root);
        setPhase("done");
      }
    } catch (error) {
      console.error("Could not initialize the desktop workspace:", error);
    } finally {
      setBusy(false);
    }
  };

  const restore = async () => {
    if (!window.desktop) return;
    setBusy(true);
    try {
      const result = await window.desktop.restoreBackup();
      if (result) setPhase("done");
    } catch (error) {
      console.error("Could not restore the desktop workspace:", error);
    } finally {
      setBusy(false);
    }
  };

  if (phase === "done") return null;
  if (phase === "splash") {
    return (
      <div className="startup-overlay startup-splash" role="status" aria-label="Document Studio is starting">
        <div className="splash-mark" aria-hidden="true"><Sparkles size={28} /></div>
        <h1>DOCUMENT STUDIO</h1>
        <p>Document Generated by M. Muneeb Ahmed</p>
      </div>
    );
  }

  return (
    <div className="startup-overlay">
      <section className="setup-dialog" role="dialog" aria-modal="true" aria-labelledby="setup-title">
        <span>First launch</span>
        <h1 id="setup-title">Set up your workspace</h1>
        <p>Choose a writable storage folder or restore a Document Studio backup ZIP.</p>
        <div className="setup-actions">
          <Button type="button" onClick={fresh} disabled={busy}><FolderOpen size={18} /> Start Fresh Setup</Button>
          <Button type="button" variant="outline" onClick={restore} disabled={busy}><ArchiveRestore size={18} /> Restore Backup</Button>
        </div>
      </section>
    </div>
  );
}